<?php
    $input = 'w-full border-2 border-gray-200 rounded-xl px-4 py-3 text-sm';
    $label = 'block text-xs font-bold text-gray-500 mb-1.5';
?>
<div class="bg-white rounded-2xl border p-5 grid grid-cols-1 sm:grid-cols-2 gap-4">
    <div class="sm:col-span-2"><label class="<?php echo e($label); ?>">اسم المشروع *</label><input name="name" required value="<?php echo e(old('name', $project->name ?? '')); ?>" class="<?php echo e($input); ?>"></div>
    <div class="sm:col-span-2"><label class="<?php echo e($label); ?>">الوصف</label><textarea name="description" rows="3" class="<?php echo e($input); ?>"><?php echo e(old('description', $project->description ?? '')); ?></textarea></div>
    <div><label class="<?php echo e($label); ?>">المدينة</label><input name="city" value="<?php echo e(old('city', $project->city ?? '')); ?>" class="<?php echo e($input); ?>"></div>
    <div><label class="<?php echo e($label); ?>">الموقع</label><input name="location" value="<?php echo e(old('location', $project->location ?? '')); ?>" class="<?php echo e($input); ?>"></div>
    <div><label class="<?php echo e($label); ?>">مساحة الأرض م²</label><input type="number" name="land_area_m2" min="0" step="0.01" value="<?php echo e(old('land_area_m2', $project->land_area_m2 ?? '')); ?>" class="<?php echo e($input); ?>"></div>
    <div><label class="<?php echo e($label); ?>">نوع العقار *</label><select name="property_type" required class="<?php echo e($input); ?>"><?php $__currentLoopData = \App\Models\Project::PROPERTY_TYPES; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $k=>$t): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($k); ?>" <?php if(old('property_type',$project->property_type??'residential')==$k): echo 'selected'; endif; ?>><?php echo e($t); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
    <div><label class="<?php echo e($label); ?>">نوع التطوير</label><select name="project_type" class="<?php echo e($input); ?>"><option value="">—</option><?php $__currentLoopData = \App\Models\Project::DEVELOPMENT_TYPES; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $k=>$t): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($k); ?>" <?php if(old('project_type',$project->project_type??'')==$k): echo 'selected'; endif; ?>><?php echo e($t); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
    <div><label class="<?php echo e($label); ?>">حالة العرض *</label><select name="listing_status" required class="<?php echo e($input); ?>"><?php $__currentLoopData = \App\Models\Project::LISTING_STATUSES; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $k=>$t): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($k); ?>" <?php if(old('listing_status',$project->listing_status??'active')==$k): echo 'selected'; endif; ?>><?php echo e($t); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
    <div><label class="<?php echo e($label); ?>">إجمالي الوحدات</label><input type="number" name="total_units" min="0" value="<?php echo e(old('total_units', $project->total_units ?? 0)); ?>" class="<?php echo e($input); ?>"></div>
    <div><label class="<?php echo e($label); ?>">السعر من</label><input type="number" name="price_from" min="0" value="<?php echo e(old('price_from', $project->price_from ?? '')); ?>" class="<?php echo e($input); ?>"></div>
    <div><label class="<?php echo e($label); ?>">السعر إلى</label><input type="number" name="price_to" min="0" value="<?php echo e(old('price_to', $project->price_to ?? '')); ?>" class="<?php echo e($input); ?>"></div>
</div>
<?php /**PATH C:\xampp\htdocs\afaq\resources\views\developer-portal\projects\partials\form.blade.php ENDPATH**/ ?>